#!/bin/bash

brew install aiccu
brew install aircrack-ng
brew install archey
brew install aria2
brew install atk
brew install autoconf
brew install automake
brew install autossh
brew install bison
brew install bison27
brew install brew-cask
brew install cairo
brew install cmake
brew install composer
brew install cups-pdf
brew install dcraw
brew install dialog
brew install dirmngr
brew install docker
brew install f3
brew install faac
brew install ffmpeg
brew install flex
brew install fontconfig
brew install fortune
brew install freetype
brew install fswatch
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install git
brew install glib
brew install gmp
brew install gnupg
brew install gnupg2
brew install go
brew install gobject-introspection
brew install gpg-agent
brew install grep
brew install gtk+
brew install harfbuzz
brew install htop-osx
brew install icu4c
brew install iftop
brew install imagemagick
brew install iperf
brew install irssi
brew install jasper
brew install jpeg
brew install lame
brew install libassuan
brew install libav
brew install libevent
brew install libffi
brew install libgcrypt
brew install libgpg-error
brew install libksba
brew install libmicrohttpd
brew install libplist
brew install libpng
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libvo-aacenc
brew install libxml2
brew install libzip
brew install little-cms
brew install little-cms2
brew install lua
brew install mad
brew install mariadb
brew install mcrypt
brew install media-info
brew install mhash
brew install mobile-shell
brew install mono
brew install mplayer
brew install mutt
brew install nmap
brew install node
brew install openssl
brew install p7zip
brew install pango
brew install pcre
brew install peco
brew install php-cs-fixer
brew install php53-intl
brew install php56
brew install php56-xdebug
brew install phpdocumentor
brew install phpunit
brew install pinentry
brew install pixman
brew install pkg-config
brew install protobuf
brew install pth
brew install pv
brew install py2cairo
brew install pygobject
brew install pygtk
brew install python
brew install qt
brew install re2c
brew install readline
brew install rtmpdump
brew install s-lang
brew install serf
brew install sl
brew install sox
brew install sqlite
brew install ssh-copy-id
brew install subversion
brew install t1lib
brew install texi2html
brew install tmux
brew install tokyo-cabinet
brew install ufraw
brew install unixodbc
brew install unrar
brew install usbmuxd
brew install watch
brew install wget
brew install x264
brew install xvid
brew install xz
brew install yasm
brew install zbar
brew install zlib
brew install zsh
