#!/bin/bash

brew cask install adium
brew cask install airserver
brew cask install arq
brew cask install atom
brew cask install bartender
brew cask install bettertouchtool
brew cask install bittorrent-sync
brew cask install charles
brew cask install chatology
brew cask install colloquy
brew cask install crashplan
brew cask install crashlytics
brew cask install cyberduck
brew cask install dash
brew cask install dropbox
brew cask install fantastical
brew cask install firefox
brew cask install flux
brew cask install google-chrome
brew cask install google-earth-pro
brew cask install handbrake
brew cask install inkscape
brew cask install insomniax
brew cask install jabref
brew cask install keepassx
brew cask install keyboardcleantool
brew cask install language-switcher
brew cask install macdown
brew cask install mediaelch
brew cask install mediathekview
brew cask install moneymoney
brew cask install monolingual
brew cask install mou
brew cask install omnidisksweeper
brew cask install opera
brew cask install origin
brew cask install phpstorm
brew cask install pref-setter
brew cask install prezi
brew cask install sdformatter
brew cask install seil
brew cask install selfcontrol
brew cask install sequel-pro
brew cask install shortcat
brew cask install skype
brew cask install spotify
brew cask install steam
brew cask install sublime-text
brew cask install tv-browser
brew cask install teamviewer
brew cask install telephone
brew cask install testflight
brew cask install texpad
brew cask install textexpander
brew cask install textwrangler
brew cask install the-unarchiver
brew cask install thunderbird
brew cask install time-tracker
brew cask install today-scripts
brew cask install transmission
brew cask install vlc
brew cask install virtualbox
brew cask install wireshark
brew cask install xnviewmp
brew cask install xtrafinder
brew cask install yummy-ftp
brew cask install zipeg
brew cask install ibettercharge
brew cask install iexplorer
brew cask install owncloud
brew cask install texmaker
brew cask install texstudio
brew cask install quicklook-csv
brew cask install quicklook-json
brew cask install xca
brew cask install disk-inventory-x

